name: yolov11_seg
channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - cudatoolkit=12.8     
  - pytorch=2.7.1
  - torchvision=0.22.1
  - torchaudio=2.7.1
  - opencv
  - pip
  - pip:
    - ultralytics==8.3.161
    - label-studio==1.19.0
    - albumentations==2.0.8
