name: yolov11_seg
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pytorch=2.7.1
  - opencv
  - pip
  - pip:
    - torchvision==0.22.1+cu128
    - torchaudio==2.7.1+cu128
    - ultralytics==8.3.161
    - albumentations==2.0.8
    - label-studio==1.19.0
